{#if type=='checkbox'}
    <span class="w-3 h-3 justify-center content-center inline-flex items-center rounded-sm dark:border-white dark:text-white border-gray-900 text-gray-900 border p-0 m-0 mr-1">
        <svg xmlns="http://www.w3.org/2000/svg" class:hidden={!checked} class="h-3 w-3 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
        </svg>
    </span>
{:else}
    <label>
        <span class="hidden">Input Generated By Markdown</span>
        <input {type} {disabled} {checked}>
    </label>
{/if}

<script>
export let disabled=undefined;
export let type;
export let checked=undefined;
</script>